### PR TITLE
refactor reapyr

### PR DESCRIPTION
**Pull request by sDos280**
refactored .gitignore file
refactor examples
updated docs

### CODE REVIEW

**Review by stucotso — CHANGES_REQUESTED** [review]
Thanks for the PR! Lots of great ideas in this one.  Few thoughts - and note most of these are just my own subjective opinions, there isn't really a right/wrong here, but would love to have your feedback if you disagree with any of them.

1. .gitignore - I like this one, seems comprehensive, thanks
2. CONVENTIONS.md - 

We're in a bit of unique position with Reapyr as it is a transpiler ecosystem - right now there is python to C++, but I have plans to merge in transpilers for other tech as well (Javascript and Lua for example). So I don't know yet if I want to use pure-Python conventions across the board yet.

Another concern, is that right now the 'raylib' Python API is intended to be a direct clone of the C API, so C conventions currently apply to the 'raylib' Python module, I wanted to do this so that developers could copy / paste code to and from Raylib C code, since it will be common for folks to be transitioning, using both or using docs from one to guide code on the other side.

So for now I'd recommend we skip this file just yet, until we get the multi-language nature of the project bit more well defined.  

I think this is needed for sure though, you've flagged an important issue here.  Especially due to the mult-language nature of Reapyr we probably need to clarify things for contributors. I'm thinking for example we could do:

raylib module - follows raylib C conventions (note we may move this to reapyr.raylib to prevent collision with cpython libs
'reapyr' module - this will contain many other modules - for supplemental code like physics, networking, etc.  these modules will be transpiled to many languages, so another set of conventions needed here.

3. Moving examples/raylib to examples/

I had moved these out as there are many other examples yet to come, for example for 'reapyr' modules that are not 'raylib'.   So I wanted to delineate what was raylib specific (which is code that can get copy/pasted to C) vs 'reapyr' specific, which doesn't have C counterpart yet.  Let me know thoughts on this

4. renaming raylib examples to match the C example names, and adding more raylib C examples ports to reapyr repo

Yes! I like this idea, let's move forward with those changes.

Is it possible to reformat this PR ?  Feel free to add thoughts for discussion as well! Thanks for your help here!

**Comment by sDos280** [comment]
ok 👍

about 3 and 2: ok, so, should I move the `CONVENTIONS.md` and all the example currently in the `examples/core` folder to a folder named `examples/raylib/core`? and refactor the current `CONVENTIONS.md` file to be more like the `CONVENTIONS.md` file in the raylib c repository?

**Comment by stucotso** [comment]
My thoughts here (feel free to disagree, I'm brainstorming this on the fly as your PR has motivated me to think about these things!)

1. CONVENTIONS.md -

Let's make this really short for now, ie: call out following:

'raylib' module: Mention we are aiming to keep parity with C API to ease transition of code to / from C. Maybe link to C conventions as URL in rl repo

'reapyr' module (which doesn't exist yet):  Likely to be more language neutral convention for folks that are also working/debugging from other languages (such as JS, Lua, etc.).  I'm a fan of following:

PascalCase for classes
camelCase for methods
BIG_SNAKECASE_CAPS for constants
4 spaces per tab

2. Examples refactor

yes I like the idea of raylib examples in a 'raylib' folder, and replicate folders/structures as in C repo

**Comment by sDos280** [comment]
ok 👍, a fixed PR will be out in some minutes.

**Comment by sDos280** [comment]
Is that better now?

**Review by stucotso — APPROVED** [review]
Looks great thanks!

**Pull request merged**
